#!/bin/env perl

use strict;
use warnings;
use 5.010;

use Lotto;

my $config = parse_config();

my ($type, $count) = parse_args($config, @ARGV);

for (1 .. $count) {
  my @nums = lotto($config->{$type});
  local $" = ', ';
  say join ' : ', map { "@$_" } @nums;
}
